default:
  tags: [build]

stages:
  - build

build_job:
  stage: build
  script:
    - rm -fr artifacts
    - mkdir artifacts
    - (cd src/cat && make clean && make s21_cat)
    - (cd src/grep && make clean && make s21_grep)
    - cp src/cat/s21_cat src/grep/s21_grep artifacts
  artifacts:
    paths:
      - artifacts
    expire_in: 30 days
  only:
    - develop
