default:
  tags: [build]

stages:
  - build
  - code_style

build_job:
  stage: build
  script:
    - rm -fr artifacts
    - mkdir artifacts
    - (cd src/cat && make clean && make s21_cat)
    - (cd src/grep && make clean && make s21_grep)
    - cp src/cat/s21_cat src/grep/s21_grep artifacts
  artifacts:
    paths:
      - artifacts
    expire_in: 30 days
  only:
    - develop

clang_format_job:
  stage: code_style
  script:
    - cp materials/linters/.clang-format src/cat/
    - cp materials/linters/.clang-format src/grep/
    - echo "Running clang-format check..."
    - |
      if clang-format -n --Werror --verbose src/cat/*.c src/grep/*.c; then
        echo "Clang-format check passed."
      else
        echo "clang-format check failed."
        exit 1
      fi
  only:
    - develop